install:
	javac *.java

run:
	javac *.java
	java Main
	rm *.class
	rm *.java~

clean:
	rm *.class
	rm *.java~
	
cleanWindows:
	del /f *.class
	del /f *.java~

runWindows:
	javac *.java
	java Main
	del /f *.class
